### ISSUE TITLE
Where do I pull the docker image from?

### ISSUE THREAD

**Issue by charliwest** [clambin/tado-exporter#136]
Hello there, looking to test this out, but the link for the docker images seems to be totally broken for me.

I saw a version on docker hub but it seems 2 years old.

Thanks!

**Comment by clambin** [comment]
Weird: link works for me.  You can find it under Packages, but basically, it's ghcr.io/clambin/tado-monitor:latest.

**Comment by charliwest** [comment]
Great, that worked, no idea what was going on for me!
Thanks for the help.

Now to try and figure out how to add something to prometheus....
