### ISSUE TITLE
404 error 

### ISSUE THREAD

**Issue by charliwest** [clambin/tado-exporter#137]
Sorry me again....

So I got it up and running, but get a 404 error when trying to view the url X.X.X.X:8080.

I enabled debug logs, but not getting any extra info that is helpful (to me at least)

`2023/03/02 12:22:36 INFO tado-monitor starting version=v0.12.1
time=2023-03-02T12:22:36.019+01:00 level=WARN msg="no rules found. controller will not run"
time=2023-03-02T12:22:36.019+01:00 level=INFO msg="exporter started"
time=2023-03-02T12:22:36.019+01:00 level=DEBUG msg="poller has 1 clients"
time=2023-03-02T12:22:36.020+01:00 level=INFO msg="health monitor started"
time=2023-03-02T12:22:36.020+01:00 level=DEBUG msg="poller has 2 clients"
time=2023-03-02T12:22:36.019+01:00 level=INFO msg="poller started" interval=30s
time=2023-03-02T12:23:07.017+01:00 level=DEBUG msg="update received" duration=996.719065ms
time=2023-03-02T12:23:07.017+01:00 level=DEBUG msg="update sent" clients=2
time=2023-03-02T12:23:36.519+01:00 level=DEBUG msg="update received" duration=484.880677ms
time=2023-03-02T12:23:36.519+01:00 level=DEBUG msg="update sent" clients=2
time=2023-03-02T12:24:06.493+01:00 level=DEBUG msg="update received" duration=473.811117ms
time=2023-03-02T12:24:06.493+01:00 level=DEBUG msg="update sent" clients=2
time=2023-03-02T12:24:36.493+01:00 level=DEBUG msg="update received" duration=467.540323ms
time=2023-03-02T12:24:36.493+01:00 level=DEBUG msg="update sent" clients=2
time=2023-03-02T12:25:06.530+01:00 level=DEBUG msg="update received" duration=510.668827ms
time=2023-03-02T12:25:06.530+01:00 level=DEBUG msg="update sent" clients=2
time=2023-03-02T12:25:36.479+01:00 level=DEBUG msg="update received" duration=458.502045ms
time=2023-03-02T12:25:36.479+01:00 level=DEBUG msg="update sent" clients=2 `

Any ideas what could be wrong?

```# Set to true to enable debug logging
debug: true
# Section for Prometheus exporter functionality
exporter:
    # Listener address for the Prometheus metrics server
    addr: :9090
# Section related to polling Tado for new metrics
poller:
    # How often we should poll for new metrics
    interval: 30s
# Section related to the /health endpoint
health:
    # Listener address for the /health endpoint
  addr: :8080
# Section containing Tado credentials
tado:
    username: "MYEMAIL@ADDRESS.com"
    password: "PASSWORD"
    clientsecret: "SECRECTGOESHERE"```

**Comment by clambin** [comment]
Port 8080 only exposes the /health path, which will show you the latest stats.  It's really only there as a health check.  

Not sure what you're trying to do:  you do understand this program doesn't have a UI, right? It works by exposing metrics for Prometheus for visualisation.  And has a controller to set room temp settings.

**Comment by charliwest** [comment]
Hello,
Yeah that’s also the error Prometheus gives me, that it is getting a 404 error.
So I have spun up two docker containers currently, one with this project and one with prometheus. Prometheus is set up to monitor itself to test its working, and for that it gets results. For this one it gives me the same 404 error.
I also appreciate it’s just you and not some big open source project :) so any help is gratefully received. If the answer is “i don’t have time for this” that’s fine with me.

**Comment by clambin** [comment]
No worries: we all have to start somewhere. :) 

I was typing up a long response to walk you down the process, but then I noticed the README is a bit confusing:

```
scrape_configs:
- job_name: tado
  static_configs:
  - targets: [ '<tado host>:8080' ]
```

Tado-monitor's default port for Prometheus metrics is 9090.  Does it work if you change the target to [ '<tado host>:9090' ]?

**Comment by charliwest** [comment]
That seems to have done it! Thanks so much for your help.

On another note, the guide shows the variables:-

export TADO_MONITOR_TADO.USERNAME="username@example.com"
export TADO_MONITOR_TADO.PASSWORD="your-password"

It would be good to also have:-

TADO_MONITOR_TADO.CLIENTSECRET="loncodehere"

I can make another "issue" but just thought I would mention it. Now off to get grafana working. Thanks again for this repo, the work on it and the help here!

**Comment by charliwest** [comment]
I tried putting TADO_MONITOR_TADO.CLIENTSECRET in but it failed to authorise. When I put the details in the config file it just works fine.

**Comment by charliwest** [comment]
<img width="1441" alt="Screenshot 2023-03-09 at 13 21 27" src="https://user-images.githubusercontent.com/7933076/224021764-87678846-cda1-44ee-ac2e-c711a43e43d1.png">
woohoo!
