### ISSUE TITLE
Docker: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by pimhofman** [clambin/tado-exporter#7]
I get a similar error when trying to start a Docker container based on your last five or so images. This happens on both Ubuntu server 20.04 and macOS 11.2.1. What I found so far is that it might be an included package that does not exist or conflicts somehow.

I've looked for a solution and hoped to provide you one, but unfortunately I haven't found _the solution_ yet. I did find some things that might be relevant; https://stackoverflow.com/questions/49079981/golang-app-in-docker-exec-user-process-caused-no-such-file-or-directory
I hoped you might have an idea. Let me know if I can be of any help to you.

Ubuntu server 20.04: standard_init_linux.go:211: exec user process caused "no such file or directory" 
macOS 11.2.1: standard_init_linux.go:219: exec user process caused: no such file or directory

**Comment by clambin** [comment]
interesting.  I used to link them statically, but somehow along the lines I seem to have dropped that.  I built an image with static linking.  Seems to work on my Mac.  Could you try clambin/tado-monitor:xbuild and see if that one fixes that problem?

**Comment by pimhofman** [comment]
It's working now! :) My output is now as expected: usage: tado-monitor --config=CONFIG [<flags>] ...

Thank you for your fast service! :)

**Comment by clambin** [comment]
@pimhofman you're welcome. TBH I never realised anyone else was using these.  Guess I'll need to be more careful from now on.  :)

**Comment by pimhofman** [comment]
@clambin There are about 5.2k pulls on [Docker Hub](https://hub.docker.com/r/clambin/tado-monitor), so there a probably more people using it. :) There should be some GitHub clone and visitor stats for you in [Insights](https://github.com/clambin/tado-exporter/graphs/traffic) too.

I hope to achieve a form of auto away functionality with your tool. It looks like it can switch to away mode for a room based on status of a device, but when the entire household is away it can globally use the away mode, I'd say. That way it doesn't need a temperature value in the config but just grab the one configured in Tado config. Meanwhile the current solution has some benefits too, as we have two home offices that I'd like to control separately based on who's in.

I think Tado is great, but their auto-assist subscription is a pretty disrespectful way to earn some extra money from it's users who often already paid a nice amount. Instead of automatically switching to away mode, it moves the functionality behind a button until you pay 2,99/month. I do understand that subscription revenues make for a long-term steady income though, but the value simply isn't there now in my opinion. Happy to see that people are fixing that. :)

**Comment by clambin** [comment]
> @clambin There are about 5.2k pulls on [Docker Hub](https://hub.docker.com/r/clambin/tado-monitor), so there a probably more people using it. :) There should be some GitHub clone and visitor stats for you in [Insights](https://github.com/clambin/tado-exporter/graphs/traffic) too.

I did monitor that at some point, and the pulls were fairly constant, so I always chalked it up to some mirroring going on.  insights are also fairly low.  You just may be my only user.  :)

> I hope to achieve a form of auto away functionality with your tool. It looks like it can switch to away mode for a room based on status of a device, but when the entire household is away it can globally use the away mode, I'd say. That way it doesn't need a temperature value in the config but just grab the one configured in Tado config. Meanwhile the current solution has some benefits too, as we have two home offices that I'd like to control separately based on who's in.

Indeed, I haven't implemented a home-level auto away yet. TBH, with covid lockdown there's always *someone* home, so I haven't had much use for it.  But it is on the backlog for sure.
